name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.event.pull_request && format('ci-pr-{0}', github.event.pull_request.number) || 'ci-push-main' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Build and Pack"
        run: yarn build:prod

      - name: "Upload vsix"
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: image_services_vscode_extension
          path: packages/vscode-extension/dist/image_services_vscode_extension_0.0.0.vsix
